version: '3.4'
services:
  php:
    container_name: php
    build:
      context: ./
    ports:
      - 9000:9000
    tty: true
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
  
  nginx:
    container_name: nginx
    image: nginx:1.17-alpine
    ports:
      - 10080:80
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html

  mariadb:
    container_name: mariadb
    image: mariadb:10.4.11
    ports:
      - 33060:3306
    depends_on:
      - php
    environment:
      - MYSQL_ROOT_PASSWORD=password
    
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:edge-4.9
    ports:
      - 10081:80
    depends_on:
      - mariadb
    environment:
      - PMA_PORT=3306
      - PMA_HOST=mariadb